version: '3'

services:
    gateway-api:
        build: ./gateway-api
        container_name: "gateway-api"
        ports:
            - 8080:8080
        depends_on:
            - app
        links:
            - app
    app:
        build: ./app
        container_name: "app-node"
        depends_on:
            - mongodb
        ports:
            - 3001:3001
        links:
            - db
    db:
        image: mongo:latest
        container_name: "db"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            - SESSION_SECRET=NodeAppApi
            - MONGO_URL=mongodb://db:27017/users
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --bind_ip_all --smallfiles --logpath=/dev/null # --quiet
    redis:
        container_name: redis
        image: redis:latest
        ports:
          - "6379:6379"
        volumes:
          - ../data/redis:/data
        restart: always